[build]
  command = "npx prisma generate && cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[functions]
  directory = "netlify/functions"
  included_files = ["prisma/**/*", "node_modules/.prisma/**/*", "node_modules/@prisma/client/**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
